//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioTourikeep
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class SITIOS
    {
        [DataMember]
        public int Id_sitio { get; set; }
        [DataMember]
        public string Nombre { get; set; }
        [DataMember]
        public string Descripcion { get; set; }
        [DataMember]
        public string Direccion { get; set; }
        [DataMember]
        public string Codigo_postal { get; set; }
        [DataMember]
        public string Provincia { get; set; }
        [DataMember]
        public string Coordenadas { get; set; }
        [DataMember]
        public string Telefono { get; set; }
        [DataMember]
        public string Categoria { get; set; }
        [DataMember]
        public string Sub_Categoria { get; set; }
        [DataMember]
        public Nullable<double> Valoracion_media { get; set; }
        [DataMember]
        public string Foto { get; set; }
    }
}
